spring.application.name=catalogo-productos
server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://dpg-d8lpe4navr4c738s1k3g-a.oregon-postgres.render.com:5432/catalogo_db_rre6?sslmode=require}
spring.datasource.username=${DB_USER:catalogo_db_rre6_user}
spring.datasource.password=${DB_PASS:w5slAoxY8pJzlD4uXLKRH72ZI71j5zq4}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=${CLOUDINARY_NAME:damtmt4wx}
cloudinary.api-key=${CLOUDINARY_KEY:899475673616475}
cloudinary.api-secret=${CLOUDINARY_SECRET:1ieEW0lpDu11iCVsIck2bP-Ypzk}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.thymeleaf.cache=false